name: Kernel Builder
permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      KSU:
        type: string
        required: true
      SUSFS:
        type: string
        required: true
      LXC:
        type: string
        required: true
      VERBOSE:
        type: string
        required: true
      NOTIFY:
        type: string
        required: true

  workflow_dispatch:
    inputs:
      KSU:
        description: "KernelSU variant"
        default: "NONE"
        type: choice
        options: ["NONE", "NEXT", "SUKI"]

      SUSFS:
        description: "Enable SUSFS"
        default: "false"
        type: choice
        options: ["false", "true"]

      LXC:
        description: "Enable LXC"
        default: "false"
        type: choice
        options: ["false", "true"]

      VERBOSE:
        description: "Enable verbose output"
        default: "false"
        type: choice
        options: ["false", "true"]

      NOTIFY:
        description: "Notify build on Telegram"
        default: "true"
        type: choice
        options: ["false", "true"]

env:
  DEBIAN_FRONTEND: noninteractive
  FORCE_COLOR: "1"
  TTY_COMPATIBLE: "1"
  TERM: xterm-256color

jobs:
  default:
    runs-on: ubuntu-latest
    env:
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Fail SUSFS requirement check
        if: ${{ inputs.SUSFS == 'true' && inputs.KSU == 'NONE' }}
        run: |
          echo "Cannot use SUSFS without KernelSU"
          exit 1

      - name: Checkout code & init submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v6.3.1
        with:
          python-version: '3.12'
          enable-cache: true
          cache-suffix: "gki-builder"
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Create venv & Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -qq bc bison ccache curl flex git tar wget aria2

          uv venv
          uv sync --frozen --no-install-project

      - name: Build
        env:
          KSU: ${{ inputs.KSU }}
          SUSFS: ${{ inputs.SUSFS }}
          LXC: ${{ inputs.LXC }}
          VERBOSE_OUTPUT: ${{ inputs.VERBOSE }}
        run: |
          uv run run.py build

      - name: Import exported environment
        id: build
        run: |
          # ====== build github outputs table:
          # output          Output directory
          # version         Kernel version
          # variant         Variant suffix
          # susfs_version   SUSFS version
          # ksu_version     KernelSU version
          # toolchain       Toolchain version
          # build_time      Build timestamp

          ENV_FILE="$GITHUB_WORKSPACE/github.env"
          [[ -f "$ENV_FILE" ]] || { echo "::error::$ENV_FILE missing"; exit 1; }
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            value=${value//\'/}
            echo "$key=$value"
            echo "$key=$value" >> "$GITHUB_OUTPUT"
          done < $ENV_FILE

      - name: Upload final artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ESK${{ steps.build.outputs.variant }}
          path: |
            ${{ steps.build.outputs.output }}/ESK-${{ steps.build.outputs.version }}${{ steps.build.outputs.variant }}-AnyKernel3.zip
            ${{ steps.build.outputs.output }}/ESK-${{ steps.build.outputs.version }}${{ steps.build.outputs.variant }}-boot.img

      - name: Notify Telegram
        if: ${{ inputs.NOTIFY == 'true' }}
        env:
          VERSION: ${{ steps.build.outputs.version }}
          BUILD_DATE: ${{ steps.build.outputs.build_time }}
          KSU_VARIANT: ${{ inputs.KSU }}
          LXC: ${{ inputs.LXC }}
          SUSFS_VERSION: ${{ steps.build.outputs.susfs_version }}
          KSU_VERSION: ${{ steps.build.outputs.ksu_version }}
          TOOLCHAIN: ${{ steps.build.outputs.toolchain }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          RUN_LINK="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          MESSAGE=$(cat <<EOF
          Kernel CI

          ðŸ§ *Linux Version*: $VERSION
          ðŸ“… *Build Date*: $BUILD_DATE
          ðŸ”° *KernelSU*: $KSU_VARIANT | $KSU_VERSION
          ðŸŽ­ *SUSFS*: $SUSFS_VERSION
          ðŸ“¦ *LXC*: $([ "$LXC" = "true" ] && echo "Included" || echo "Disabled")
          ðŸ› ï¸*Toolchain*: $TOOLCHAIN

          [Workflow Run]($RUN_LINK)
          \#ci\_$GITHUB_RUN_ID
          EOF
          )

          curl -s -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TG_CHAT_ID}" \
            -d disable_web_page_preview=true \
            -d parse_mode=Markdown \
            -d "text=${MESSAGE}"
